### PR TITLE
Add CI/CD and NuGet publishing

### PR DESCRIPTION
**Pull request by gmantaos**
As per what was briefly discussed on [gitter](https://gitter.im/Nez-Devs/Lobby), this PR adds a proposed method for Nez to get a CI/CD pipeline and a release system through NuGet. Users of the framework can then use Nez by getting the latest stable version off of NuGet, without having to rely on the current state of the master branch, to burden their project with the entirety of Nez's codebase or to make their own workflow more complicated by carrying around clunky and volatile submodules.

With this proposal, the project gets a proper release system, with which maintainers can put out a new version of stable builds using `git tag`, or equivalently GitHub releases. These versions are automatically built and published using a new introduced pipeline for AppVeyor. The changes introduced can be broken up into the following sections. 

### 1. Added `.nuspec` files for package metadata.

Each of the projects under the solution got its own `.nuspec` file. Normally, these files only contain metadata, so that the `nuget pack [...].csproj` can locate it by having the same name and use it to build the package. This way, MSBuild is responsible for deciding what goes in the package. However we don't want this for Nez, as building a nuget package out of the `.csproj` files would also add [MonoGame.Framework.Portable](https://www.nuget.org/packages/MonoGame.Framework.Portable/) as a package dependency, causing anyone who installs the package to also essentially add a reference to a fakes assembly, instead of the `DesktopGL` or platform-equivalent that he should use instead. Instead, I've used `<dependencies>` and `<files>` nodes, so that each `.nuspec` file can fully describe the package, which is built with `nuget pack [...].nuspec`.

The `Nez.PipelineImporter` project was treated differently. The four `dll` files that it carries, which need to be referenced by `Content.mgcb`, were manually defined in the `<files>` section. Doing so with a target other than `lib`, causes these files to be downloaded by NuGet when installing the package without adding references to them. This way a user immediately gains access to these files, which he can then reference in `Content.mgcb`, as it is explained in the [updated README.md](https://github.com/gmantaos/Nez/blob/nuget-ci/README.md).

Lastly, the contents from `DefaultContent` are also included in the `Nez` package, under a `tools` directory.

You may also want to review the metadata, to check if the descriptions and tags are as you'd like them.

### 2. Enabled XML documentation for the Nez projects.

This was enabled via the `XML documentation file` option under the project settings for each of the projects in the solution. This causes an additional `.XML` file to appear when building the project, which contains all of the `<summary>` documentation defined in the project's classes. This file now gets included in the NuGet package, which is now necessary for the documentation to be visible to the user since the library will no longer be a local project reference in Visual Studio.

### 3. Added AppVeyor pipeline.

The new `appveyor.yml` file contains the description of the CI/CD pipeline, which once you add the necessary webhook will run each time there's a push to the repo. The pipeline in itself is very basic and for generic pushes will only build the solution, thus updating its status for the badge that will be described further down. the pipeline also contains a `deploy` stage, which will publish the build NuGet packages on new git tags. You can check out how this works on [my fork's pipeline](https://ci.appveyor.com/project/gmantaos/nez).

**PS:** The `msbuild.rsp` file is how AppVeyor accepts parameters to pass to MSBuild. Removing this and raising the warning level will cause the pipeline build time to grow significantly, since it attempts to log thousands of warnings of public members that are missing their XML documentation.

### 4. Updated README.md

I have also [updated the README.md](https://github.com/gmantaos/Nez/blob/nuget-ci/README.md).to include some basic instructions on how to install Nez through NuGet, a badge with the AppVeyor pipeline status for the master branch, as well as two NuGet bagdes containing the latest version and the amount of downloads. These will all show up as gray until AppVeyor is configured for the project and the first NuGet version is pushed.

## Steps required from you before merging.

1. Create a [nuget.org](https://www.nuget.org/) account if you don't have one already.
2. Add a [new API key](https://www.nuget.org/account/apikeys) with a glob pattern of `*` or `Nez*` and the `Push new packages and package versions` scope.
3. Login to [ci.appveyor.com](https://ci.appveyor.com/), preferably with your GitHub account so that the badge paths match.
4. Add the `Nez` project to AppVeyor through the dashboard, this will set the appropriate webhooks on the project on GitHub.
5. Use [this tool](https://ci.appveyor.com/tools/encrypt) to encrypt your NuGet API key.

The encrypted API key now goes into `appveyor.yml` and is decrypted in secret when AppVeyor attempts to push the built packages to NuGet. When you have it, you can post it here or send it to me on gitter and we can proceed with this merge once it's added.

I would also recommend squashing during the merge, as there are quite a few trial-and-error commits in here.

Cheers :)

### CODE REVIEW

**Comment by prime31** [comment]
Solid work on this PR! I merged it into a branch (nuget-ci) and added the NuGet key to the appveyor.yml file. The push triggered a build that succeeded but with this message:

> "NuGet"` deployment has been skipped as environment variable has not matched ("appveyor_repo_tag" is "false", should be "true")

`appveyor_repo_tag` is set to true in the appveyor.yml file. Any idea why it didnt deploy to NuGet? I must be missing something simple here!

**Comment by gmantaos** [comment]
First of all I made a mistake and [L44](https://github.com/prime31/Nez/blob/nuget-ci/appveyor.yml#L44) was missing indentation. Fixed it on my branch so you should merge one more time, sorry about that.

---

Yes this is intended, but I can see where the confusion came from. The last lines in `appveyor.yml` work like this:

```yml
deploy:
- provider: NuGet
  on:    # Defines conditions for when to deploy
    appveyor_repo_tag: true    # Only deploy when '$appveyor_repo_tag' is set
                               # which means only on git tags
  api_key:
    secure: "RKBT0c+TQ77H48syafSTzgyYeYIDBuZcnj+wg00dVIkLPNwuutPTniO9BOz/jM72"
```

This way you don't get a new NuGet package for every push to master. Instead, when you know you have a stable branch, you use `git tag` (or equivalently a GitHub release). Then the name of the tag is passed to `nuget pack`, specifying the version of the package. So assuming you want the first published version of Nez to be `0.10.0`, simply add a tag or release named `0.10.0` and it will attempt to deploy. You should be able to do it with a tag on the `nuget-ci` branch.

**Comment by prime31** [comment]
Looks good. I just did a test build with `appveyor_repo_tag` `false` and everything built and released on NuGet successfully. Well done on this PR!

**Comment by gmantaos** [comment]
Thanks for the quick merge :)

There's still one more issue I forgot to mention. The `Nez.FarseerPhysics` package depends on `Nez` and with what I mentioned under under number `1.` in the PR, such dependencies have to be hard-coded in the `.nuspec` file. So right now, any installation of `Nez.FarseerPhysics` may sometimes fail, since as shown on [this line](https://github.com/prime31/Nez/blob/7489705e1eb9a7ebc5daf1a7e74ca7a4b85fc6be/Nez.FarseerPhysics/Nez.FarseerPhysics.nuspec#L16) it depends on a `Nez.0.9.0`, which currently doesn't exist. Therefore this line needs to be manually updated just before pushing out a new version, with the version that is about to be pushed.

Also, it probably may be worth it to move on from the `0.9.*` version, since there's generally never a reason not to follow [semver](https://semver.org/).

**Comment by prime31** [comment]
I'll whip up a quicky little build script to handle that. Zero chance I will remember every time ;)

**Comment by gmantaos** [comment]
Ye, I like this approach more. You could call it in the `if %APPVEYOR_REPO_TAG%` block, or move the NuGet packing to the `before_deploy`, in which case you wouldn't need an `if`, since that stage only runs for tags.

**Pull request merged**
