### PR TITLE
Fixes bug where renderables added by a component can cause a crash

### LINKED ISSUE #202: setMaterial/setLayerDepth unsafe on sub-components in onAddedToEntity
Steps to reproduce:

- Make a new Component that implements onAddedToEntity, in which it adds a RenderableComponent (ie Sprite) and calls setMaterial/setLayerDepth on it
- In Scene init add a single Entity with the Component
- Crashes at RenderableComponentLists::updateLists

The crash occurs because setMaterial/setLayerDepth immediately notifies RenderableComponentList that a layer is unsorted before the RenderableComponent itself has been propogated into _componentsByRenderLayer (thereby initialising that key => FastList), causing a KeyNotFoundException in RenderableComponentLists::updateLists.

I suspect the fix is to just add a contains check to RenderableComponentLists::updateLists and only remove the layer from _unsortedRenderLayers when its propagated and able to be sorted, but would appreciate your opinion here.

Edited for clarity.

### PR DESCRIPTION
**Pull request by Vanit**
Resolves #202

### CODE REVIEW

**Comment by prime31** [comment]
This looks like a good fix. If you could just fix the formatting I can get it merged. There is a policy file in the root of the repo with formatting details if you prefer to use them.

**Comment by Vanit** [comment]
Sorry for being super slow on this, went on leave! I'm actually using Visual Studio so I'm not sure what I can do with that policy file. I can make a best effort to make the style match, but other times I've done that in the PR the diff doesn't look quite right. I'll take a shot at it and hopefully that's good enough.

**Comment by Vanit** [comment]
Been on hiatus, but I finally got around to attempting to fix this up. Admittedly the indenting still looks wrong, but I'm not sure what the issue is. As discussed, I'm using VS so I can't use the style policy.

**Comment by dsusini** [comment]
Hey Vanit.  I uploaded a policy file specifically for Visual Studio a couple of months ago.  It should work for your needs.  Depending on your VS version, you may have to edit the version text at the top of the file; it is setup for VS 2015.  Let me know if it gives you any issues.

**Comment by Vanit** [comment]
@dsusini Oh hey, so there is! Thanks, I'll check that out.

**Comment by Vanit** [comment]
Thanks @dsusini. I'm using 2015 so it worked great.

@prime31 the format is now correct, can you merge?

**Pull request merged**
