### PR TITLE
Fix sprite animator

### LINKED ISSUE #832: Different framerate for each frame is bugged
Hi, I found out that if you use different framerates for each frame of your animation, the animation get's totally bugged.

Let's take this spritesheet as an example:

Hop-Anim

You can reproduce the bug with a code like this:

```csharp   
        var texture = Content.LoadTexture(@"Content\Sprites\Outfits\1\Hop-Anim.png");
        var atlasSprites = Sprite.SpritesFromAtlas(texture, 32, 80);
            
        var entity = CreateEntity("SpriteExample", Screen.Center);

        var animator = entity.AddComponent<SpriteAnimator>();
        Camera.SetZoom(Camera.MaximumZoom);

        var frameRates = new float[]
        {
            30,
            60,
            30,
            20,
            15,
            15,
            20,
            30,
            60,
            30
        };

        var sprites = new[]
        {
            atlasSprites[0],
            atlasSprites[1],
            atlasSprites[2],
            atlasSprites[3],
            atlasSprites[4],
            atlasSprites[5],
            atlasSprites[6],
            atlasSprites[7],
            atlasSprites[8],
            atlasSprites[9],

        };

        var spriteAnimation = new SpriteAnimation(sprites, frameRates);
        
        animator.AddAnimation("Run", spriteAnimation);
        
        animator.Play("Run");
```

And you should see your animation getting bugged like this:

https://github.com/user-attachments/assets/10329283-0840-46fe-81dd-d346aa9b7e7d

But if you simply change your frameRates array so that every frameRate is the same:

image

Now your animation works fine:

https://github.com/user-attachments/assets/6a85ad55-4323-4b35-88f7-4cf56ef350e6

### PR DESCRIPTION
**Pull request by ricardoianelli**
Fixes #832 

Used exactly the same spritesheet and same code from the [issue](https://github.com/prime31/Nez/issues/832).
Now everything works fine.

Re-wrote the changes a second time to fit the request to have things more coupled and all in the same class. 

Recorded again and uploaded new evidence that everything works fine for each of the LoopModes.

If possible, I would like to ask if someone could test the Aseprite import thing to ensure it also works that way, and check with one of your games to see if the animations still play in the speed they used to. I tested on the Ninja Adventure sample and it looks good too, but since it's my first time using Nez and I haven't made any game on it yet, it's nice to double check.

### Loop

https://github.com/user-attachments/assets/9db0257b-f67b-42e4-9429-26dedf2bebaf

### Once

https://github.com/user-attachments/assets/4ffa7727-2fc1-498a-993c-e79f58b3fc69

### ClampForever

Since the first and last frames are the same, I added a little more evidence for this one.

https://github.com/user-attachments/assets/19c6f563-9f55-4bdf-a459-9d7e4c6c8a1b

image

### PingPong

https://github.com/user-attachments/assets/aa4a5048-12af-4c43-b712-91a0082c3d27

### PingPongOnce

https://github.com/user-attachments/assets/1b417511-1125-419e-8951-1eda3975351b

### CODE REVIEW

**Comment by prime31** [comment]
Continuing the discussion from Discord here. The code all looks solid. The only issue I really see here is that there are a bunch of "forced design pattern decouplings" that don't really fit in with the Nez codebase. We generally don't mind coupling here. It's a game framework designed to be readable so avoiding abstractions and instead choosing coupling reduces extra types, decreases indirection and keeps things all in one file when possible.

If you prefer all the abstractions I'd say its best to keep the updates in your branch. If you still would like to push your changes here there are just a few small things that I would like to see:
- stick tiny enums right in the same file they are used (makes finding things a lot easier for new folks)
- move all the LoopControllers into a single switch (another simplification and coupling for simplicity/speed/memory)

**Comment by ricardoianelli** [comment]
@prime31 Moved everything back to the same class, re-tested everything and re-uploaded evidences.

**Comment by ricardoianelli** [comment]
> > @prime31 Moved everything back to the same class, re-tested everything and re-uploaded evidences.
> 
> thanks for doing that. just wanted to note I think it doesnt need to be a partial class now?

You're welcome. Ohh, I forgot that, thanks for catching this detail! I'll remove it and commit, thanks!

**Comment by prime31** [comment]
Looks good!

**Pull request merged**
