### PR TITLE
Added Cake

### PR DESCRIPTION
**Pull request by RabdPnguin**
Added simple Cake build script for building projects and creating nuget packages.
* Tested and working on Windows.
* Includes script to build on linux/mac but untested.

https://cakebuild.net/

### CODE REVIEW

**Comment by RabdPnguin** [comment]
I set the nuget package versions to 1.0.0 (in the nuspec files); they can be updated to reflect the assembly versions or the build.cake file can be updated to pull the version number from AssemblyInfo.cs if this would be preferable.

**Comment by Vanit** [comment]
I'm going to assume this PR is kind of doubling as a proposal to start releasing more nuget builds, which Nez hasn't done for a while.

@prime31 I'm not sure if there's anything like an official roadmap for Nez - are you even interested in doing nuget builds anymore, or just keeping Nez as a develop type thing? This PR seems to be more in the purview of what you should be committing yourself if/when a decision is made?

**Comment by RabdPnguin** [comment]
Yeah. Its not such a big deal. It's just sometimes easier to use a nuget
package rather than referencing the whole project.

**Comment by Vanit** [comment]
@prime31 Comments?

**Comment by prime31** [comment]
I suppose it may be useful for someone out there but I personally don't think it should be in the main branch. NuGet is just too limited for something like Nez and any MonoGame additions that have Content. All the textures and effect files would then just throw confusing errors for folks trying to just pull the NuGet package and not realizing there are other files required.

**Comment by RabdPnguin** [comment]
Why would they throw exceptions? Nez specific content content files can be
included in the nuget package.

**Comment by prime31** [comment]
They would throw Exceptions due to the files not being present, linked and setup in the csproj file to be built copied along with the rest of the MonoGame content.

**Comment by RabdPnguin** [comment]
You can do that in a nuget package. You can include content.

**Pull request closed without merging**
