### PR TITLE
Streamlined UISkin Pipeline to make it more Robust and to Add more libGDX Skin Compatibility

### PR DESCRIPTION
**Pull request by dsusini**
When loading a UISkin with nested styles Nez would crash because it was hard-coded to 2 nested Dictionary<string, string> levels.  I've removed this limitation by recursively loading through Dictionary<string, object>s.  

To reproduce this issue in the current version, you can try loading the follow skin style:

```
SelectBoxStyle: 
{
	default: 
        {
            background: 'default-select', 
            scrollStyle: 'default', 
            listStyle: {font: 'default-font', fontColorSelected: 'white', fontColorHovered: 'white', selection: 'list-selection', hoverSelection: 'list-selection', background: 'select-box-list-bg'},
            font: 'default-font', 
            fontColor: 'white', 
            disabledFontColor: 'gray'
        }
}, 
```
It should fail when attempting to load the listStyle.  This change should allow any depth of nested inline styles to be used in the future.

This is also an attempt, along with a few other changes, to make Nez UISkins more compatible with LibGDX Skins.  For example, UISkin Colors can now be loaded as arrays or objects of 3-4 values, Color objects can be specified using "r", "g", "b", "a" notation, and Color values can now be either bytes (0-255) or normalized float values (0.0-1.0).

```
colors: 
{
        hex:'0xFF000000',
    	black: [0, 0, 0, 255],
        arrCol: [0.1, 0.4, 0.6],
        arrColAlpha: [0.1, 0.4, 0.6, 1],
        objCol: {r: 1, g: 2, b: 3},
        objColNo: {r: 0.1, g: 0.4, b: 0.6, a: 1.0},
    	white: [255, 255, 255, 255],
    	green: [0, 255, 0, 255],
},
```

I had to include a few other small changes and bug fixes that were found in the UI system.  

Please feel free to comment and let me know if you find this helpful or would like some changes.  I plan on many more changes to the UI system to make it more in line with libGDX and Vis-UI.  If that's not a route you'd like to go, I can keep that to my own fork.

Here is an example of a window Skin I grabbed from Vis-UI and slightly modified for use in Nez.  It still needs some spacing work, but I'm going to start tackling UI features next.  Please let me know your thoughts.

nezui

### CODE REVIEW

**Comment by prime31** [comment]
This all sounds good to me. I don't know what Vis-UI is but it sounds like it may just be a custom skin so that is fine.

A couple minor comments about the PR:

- 2 files seems to have had their entire contents removed and readded resulting in zero change. If you can leave commits like that out of the PR it keeps the history much cleaner.
- there are a couple mdpolicy files in the root of the repo. When you format the code make sure to use them so that it matches the rest of the code base.

Besides those minor tidbits everything else sounds great!

**Comment by dsusini** [comment]
To be honest, I was a bit frustrated with that commit.  I didn't know how to leave it out of the PR, I'll see what I can do to clean that up.  Also, I'll make sure the code conforms to the mdpolicy.  I have a few more things I wanted to do with the UI stuff; mainly just some more cleanup and to add some features.

VisUI is just a small UI framework built in java that adds some more widgets to libgdx along with some more skinning features:
https://github.com/kotcrab/vis-editor/wiki/VisUI

Thanks for your input.

**Comment by dsusini** [comment]
Ok, I've finally gotten around to taking care of this.  

1. I updated my Visual Studio formatting settings to match your policy file and reformatted my changes. That should be taken care of now.
2. The other issue you mentioned was the project file that was completely overwritten in one of the diffs.  I'm not sure what to do about that one file, as there were other changes in that commit.  I can remember to make sure that doesn't happen next time.  If it's a deal-breaker for this PR, I would need to know the best way to remove that one file's change in that one diff and resubmit.  I'll leave that up to your discretion.  Next time, also, I will remember to keep my changes in a separate branch.

Please let me know if there's anything else I should do.  Thanks for taking the time to look at this.

**Comment by dsusini** [comment]
I've exported a .vssettings file for Visual Studio that contains most of your formatting policies.  Let me know if you'd like this checked into the repo for those that use VS.

**Comment by prime31** [comment]
Sure. It can't hurt to have formatting options for VS.

**Comment by dsusini** [comment]
ok, .vssettings policy file added.  Let me know if there's anything else I need to do.  Thanks!

**Pull request merged**
