### PR TITLE
Right click support for UI

### PR DESCRIPTION
**Pull request by witlock**

### CODE REVIEW

**Comment by RUSshy** [comment]
What about as alternative:

``OnMousePressed(Vector2 position, int button)``

0 = left
1 = middle
2 = right


instead of 2 methods

**Comment by witlock** [comment]
I think then there would be a need for a switch in many scenarios anyway and I think this is more convenient to use.

**Comment by RUSshy** [comment]
But it is breaking change

for people already using the API, they now have to rename their function, split their logic in two, and add the 2 other methods

with my solution it is much less pain, all they have to do is add the ``int button`` and remove their button detection code if they had any, that's it

i don't use C# anymore so idc, but for existing users that's an annoying change

**Comment by witlock** [comment]
I guess I could have left the original and have it trigged by both clicks. This is one quick rename on the project. I don't think that's an issue.

**Pull request merged**
