### PR TITLE
translate few docs into chinese

### PR DESCRIPTION
**Pull request by Saplonily**
translate few docs into chinese

### CODE REVIEW

**Comment by prime31** [comment]
I assume this is still a WIP PR?

**Comment by Saplonily** [comment]
> 

Yes, could you allow me to do this slowly?

**Comment by prime31** [comment]
> Yes, could you allow me to do this slowly?

Yes, of course!

**Comment by Saplonily** [comment]
Some of the documents I could do is done! sorry for the long-time waiting.

**Comment by prime31** [comment]
No worries! Many thanks!

**Pull request merged**
