### PR TITLE
added setInset fluent method to inset camera bounds

### PR DESCRIPTION
**Pull request by jbhaywood**
The reason for this change is that my gameplay area is only a portion of the window, the rest is composed of status panels and whatnot. But the way Camera bounds are calculated right now is hardcoded to use the entire viewport. So if I want to cull map tiles outside of the playable area, and for the FollowCamera to work correctly for me, I need to be able to define a custom bounding rectangle for the camera.

If there's a better way to do this, let me know. I made sure that the default is still set to the viewport, so it shouldn't break any existing usages.

### CODE REVIEW

**Comment by jbhaywood** [comment]
Oh, and I also removed incorrect return statements in the xml documentation for the fluent methods.

**Comment by prime31** [comment]
I'll have to give this one some thought. I can see what your purpose is with HUD existing around the borders of the Camera but I'm not quite sure making bounds modifiable is the right solution. On every other object bounds is a calculated value. Perhaps having a modifiable Vector4 (or new Inset struct with left/right/top/bottom values) inset that defaults to 0,0,0.0 could be a slightly better solution. The inset would serve the same purpose just without modifying the bounds directly. When the bounds is calculated it would just take the Viewport - the inset and then use that for the calculation.

**Comment by jbhaywood** [comment]
That makes sense. I'll go the inset route and do another PR.

**Comment by jbhaywood** [comment]
Updated the PR to use an inset instead of modifying the bounds.

**Pull request merged**
