### PR TITLE
make transforms not round position by default

### PR DESCRIPTION
**Pull request by EReeves**
https://github.com/prime31/Nez/issues/367

### CODE REVIEW

**Comment by prime31** [comment]
I think this is more of a documentation issue. Changing the default will cause rendering artifacts for a majority of people using Nez (anyone using a resolution policy that has a render texture that is scaled basically). Adding a note to the docs would be a preferable approach.

**Comment by EReeves** [comment]
insanity

**Comment by prime31** [comment]
What does everyone want to see for the default valu? Should Nez round positions or not by default?

**Comment by Vanit** [comment]
I think the usecase in the PR is absolutely valid, but the PR also doesn't address the problems it would create for all projects depending on the rounding. I think it would be better to somehow get the best of both worlds (e.g. maybe the transform class can keep a raw unrounded position that can be manipulated as the OP intended, while still not breaking the current position property).

**Comment by EReeves** [comment]
That's a good idea, I was thinking you could put the onus on IRenderable implementations but I think a separate variable is a better idea.

Just have a renderPosition variable that gets set instead.

**Comment by EReeves** [comment]
Didn't realize the discussion was here and not on the issue.

**Comment by EReeves** [comment]
https://github.com/prime31/Nez/pull/369

How about this？

**Pull request closed without merging**
