### PR TITLE
Components implementing

### PR DESCRIPTION
**Pull request by RobinPerris**
Adds methods for returning a list of components which can be assigned to type T

### CODE REVIEW

**Comment by RobinPerris** [comment]
Example usage:

```csharp
// loop through and activate all activatible components
var activatibles = entity.getComponentsImplementing<IActivatible>();

foreach (var component in activatibles)
    (component as IActivatible).activate();
```

**Comment by prime31** [comment]
I'm not sure I understand exactly why this is needed. The only time you need to use IsAssignableFrom is when you dont have an instance to work with (only Type objects). The getComponents method will return the exact same List of Components. It uses the *is* operator to get them on the object instance vs dropping down to using Type objects.

The following code will do the exact same things and it wont even require the cast to call activate:

```csharp
var activatibles = entity.getComponentsImplementing<IActivatible>();

foreach (var component in activatibles)
    component.activate();
```

**Comment by RobinPerris** [comment]
```csharp
public List<T> getComponents<T>() where T : class
```

The existing method fails when trying to pass through an interface.

**Comment by prime31** [comment]
The "is" operator is used which checks if any Compoment can be casted to the passed in Type which should work just fine for an interface or class. You can see it in action in the Mover.cs file's notifyTriggerListeners method which uses getComponents to find all Components implementing the ITriggerListener interface.

**Comment by RobinPerris** [comment]
Ah, so that's how you use that method signature. Very useful.

Thanks for the feedback. I'll close this.

**Pull request closed without merging**
