### PR TITLE
Can't assume that image collection tile Id exists

### PR DESCRIPTION
**Pull request by witlock**
If you delete a tile from an image collection it creates a hole in the id counter, otherwise it messes up your map so we can't use a for loop here like this.

### CODE REVIEW

**Comment by prime31** [comment]
In what scenario would the data from the tmx file have deletions with holes in the IDs?

**Comment by witlock** [comment]
When using an image collection each image gets an ID, if it readjusted the ID's after you delete something it would mess up your map.

**Comment by prime31** [comment]
So, Tiled is not providing the ids in order when exporting? Thats surprising...

**Comment by witlock** [comment]
Yep, even though I've never used "export" to export .tmx into .tmx. I just tried it and there's no difference.

**Pull request merged**
