### PR TITLE
Adding getAllEntities and getAllComponents helper methods to EntityList and ComponentList

### PR DESCRIPTION
**Pull request by jbhaywood**
There have been a number of times when I just wanted all the entities or components, mainly for serializing to disk, and having to do `entitiesOfType<Entity>()`, for example, seemed like a bunch of unnecessary type checking.

I also thought about changing `entitiesOfType<T>()` to use the new method like this, `return toArray().OfType<T>().Cast<Entity>().ToList();` but assume that's going to be slower than what you have already.

Clarified a couple summary comments that bit me early on.

And sorry about the multiple commits, I accidentally reformatted one of the files so I had to fix it.

### CODE REVIEW

**Comment by prime31** [comment]
Since you are using the ListPool why not just return the List so that the caller of the method can release the pooled list after they are done with it?

**Comment by jbhaywood** [comment]
Sounds good. I'm new to game programming and so I'm not used to thinking about things like pools. Need to do some reading on that. I'm more familiar with the "get what you need and let the GC handle it" way of working. :)

I'll update this change in a bit.

**Comment by jbhaywood** [comment]
Updated. I also went into ListPool and made the names more explicit. Probably because I'm a game programming noob, but I kept getting tripped up when looking at the code thinking all the functions were working with individual items (not lists) within a list instead of lists within a bigger list (the queue).

**Comment by prime31** [comment]
I think what might be a bit more clear would be just a single commit with getAllEntities and getAllComponents methods. Since the method is returning a List<T> rather than an array it will be more clear to folks seeing the method name.

**Comment by jbhaywood** [comment]
I've updated the method names, but I'm not sure I can squash it down to one commit at this point. What I've read online tells me it's a tricky thing to do after you've already pushed, and my Git-Fu is weak.

**Comment by prime31** [comment]
So, I ran a quick test and entitiesOfType<Entity> was almost identical in speed to skipping the is/as check. I should have tested that from the start knowing that is/as dont throw exceptions and are only a couple IL commands. We can just leave everything as is and you can just use those methods with no worries of performance issues.

**Pull request closed without merging**
