### PR TITLE
Added support for isometric Tiled maps

### PR DESCRIPTION
**Pull request by Vanit**
Resolves issue #124

I made sure to support all the same features of the orthogonal tile layer, like camera clipping, intersecting tiles, etc.

### CODE REVIEW

**Comment by Vanit** [comment]
@prime31 Is there a reason you're holding out on merging this? I noticed there were some conflicts so I brought my branch up to date.

**Comment by prime31** [comment]
It is still on my todo list! I got sidetracked with some other major changes (adding Farseer Physics and converting the Nez standard Colliders to plain old Components). I noticed that there was a bit of duplicated code between TiledTileLayer and TiledIsometricTiledLayer so I wanted to take the time to properly combine it (and keep it functional!) to avoid any duplication.

**Comment by Vanit** [comment]
No problem at all, your work is much appreciated. :)

**Comment by piedoom** [comment]
Woo!

**Comment by prime31** [comment]
Consider it a start and definitely not final! There is a bit of duplicated code between this and normal ortho layers. Some proper layered rendering support will also need to be added.

**Comment by Vanit** [comment]
Oh hey, finally merged! In using my own code one thing I realised is missing is a specific drawTile() method in the isometric layer, which is needed to allow a rendering component fine-grain control over each tile's layer depth (which is the first hurdle anyone using the existing code will hit). Will open another PR for that soon. :)

**Comment by salvadorbs** [comment]
Yeah! Great work @Vanit  👍

**Pull request merged**
